### ISSUE TITLE
Email footer is served in English, instead of 13 languages.

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-api#160] opened 2020-02-10 08:23 UTC
**What is the problem?**
There shouldn't be any untranslated links in COS email footer - these strings (Link to Platform, Privacy Policy, Empowered by) have been translated into 13 languages almost a year ago and there aren't any unmerged pull requests in API project in Github - how come translations aren't visible?

![20200210_101918](https://user-images.githubusercontent.com/34126353/74132263-df5dfd80-4bee-11ea-9d39-36b91c7097e6.jpg)

**Why is this a problem?** 
Footer contains important links, the purpose of which should be understandable to users when they view the email in their language. Translations are there, they should just be made visible.

**Possible solution.**
Pls research, why translations aren't visible and fix the bug. Thank you! 🙏

**Comment by loorm** [comment] 2020-02-25 11:51
Triage 18: replicated. Dev time ETA: 8 hours.

**Comment by ilmartyrk** [comment] 2020-04-06 09:29
Fixed  by https://github.com/citizenos/citizenos-api/commit/a218d806a230b2f71e61be97eb3757d4cb9c75aa

**Comment by KatiVellak** [comment] 2020-04-10 14:54
Legally reviewed, no impact.

**Comment by loorm** [comment] 2020-04-29 10:35
Tested. Confirmed working.

**Comment by oksks** [comment] 2020-05-12 13:50
Something's off with the footer again:
1) Part of it still lacks translation
2) The layout is seriously off

<img width="983" alt="Screenshot 2020-05-12 at 16 45 12" src="https://user-images.githubusercontent.com/34126353/81699577-3b475500-9470-11ea-87ef-6bb97be9e8bc.png">

**Comment by loorm** [comment] 2020-05-19 10:14
Assigning for Triage.

**Comment by loorm** [comment] 2020-05-25 08:18
Triage #22. Cannot reproduce. Tried in Android and Windows Desktop. @oksks Do you still have the faulty invite. Can you please forward the invite to @ilmartyrk .

**Comment by loorm** [comment] 2021-05-31 22:16
This has never been replicated. Closing issue.

**Closed by loorm** 2021-05-31 22:16 UTC
Labels: bug
