### ISSUE TITLE
User login using e-mail alias

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-api#167] opened 2020-05-05 12:17 UTC
**What is the problem?**
When user is added to a topic using an email alias, he/she could possibly not access the topic as google returns the original e-mail

**Why is this a problem?**
When someone is trying to invite somebody to a topic and doesn't know the correct e-mail (User publicly uses alias for e-mail), the user could possibly not access topic as login returns original e-mail.

**Comment by loorm** [comment] 2020-05-11 08:36
Triage 21. Need to clarify the use case in order to reproduce problem. @ilmartyrk - what do you mean by "alias"? Please tag me in reply. 

Moved to "in prep".

**Comment by ilmartyrk** [comment] 2020-05-11 09:03
@loorm for example if I have google e-mail ilmar.tyrk@gmail.com, google also has aliases for this e-mail eg. if you send mail to ilmartyrk@gmail.com or i.lmartyrk@gmail.com it will still be delivered to my mailbox. If user is added to a topic using by alias, for my example ilmartyrk@gmail.com instead of ilmar.tyrk@gmail.com I will still get the invite to my ilmar.tyrk e-mail, but I won't be able to access the topic as my user e-mail in our system isn't matching the alias.

**Comment by loorm** [comment] 2020-05-19 10:03
@ilmartyrk Got it, thanks!

Reassigning for Triage.

**Comment by KatiVellak** [comment] 2020-05-21 11:04
@ilmartyrk How can we be sure that it was correct "alias"? Maybe there is a katrin.vellak and kati.vellak and somebody misspells and writes katri.vellak and wrong person receives the invite.

**Comment by loorm** [comment] 2020-05-25 08:37
Triage 22. This needs further thinking about a solution. Related to invites and join links. Back to in preparation.

**Comment by loorm** [comment] 2021-08-31 13:02
I've thought about it. Assigning this for Triage. Don't see a reason to keep this as blocked. Two possible decisions, but both lead to closing this issue:

1. We don't do anything. Grown-up people are responsible for inputting correct e-mail addresses. I checked - when I receive the invite to an alias and then try to follow the link in the e-mail (while being logged in with my correct e-mail), the dialog window comes up and says "Log in with (alias e-mail) to accept invitation. So user can easily see, that the invitation has been sent to the wrong e-mail address and can ask whoever sent it to send another invitation to the correct e-mail address. + the problems that Kati mentioned above. If we decided we won't do anything, let's unblock and close this issue.

2. We add a feature, where user can "request access to a topic". This is already a separate, open issue https://github.com/citizenos/citizenos-fe/issues/289. If we decide to add the feature, we still need to unblock and close this issue, because the other issue already exists.

**Comment by anettlinno** [comment] 2021-09-30 07:10
Triage 46. Discussed and decided to mention the alias email issue in the Help Center. Closing the topic.

**Closed by anettlinno** 2021-09-30 07:10 UTC
Labels: bug, blocked
